default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  user: <%= ENV.fetch('DB_USER', 'rails') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'rails') %>
  pool: <%= ENV.fetch('DB_POOL', 10).to_i %>

development:
  <<: *default
  database: diamond-liquid_development

test:
  <<: *default
  database: diamond-liquid_test

production:
  database: diamond-liquid_production
